name: BuroScope
favicon: null
layout_spectrum: 0
typography_spectrum: 0.45841573481447995
title: Kwaliteit en duurzaamheid
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#5a5758'
    - '#4fbe37'
    - '#000000'
    - '#008000'
    - '#00ff00'
  brandStrength: 0
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
