name: BuroScope
favicon: null
layout_spectrum: 0.88561
typography_spectrum: 0.45841573481447995
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0
  lightness: 0.6473291816655546
  saturation: 0.2752901935018599
  rhythmicContrast: 0.5452535061631352
purpose: []
